name: Terraform Backend Bootstrap (S3)

on:
  workflow_dispatch:
    inputs:
      working_directory:
        description: "Terraform Bootstrap Directory"
        required: true 
        default: terraform/
      
      aws_region:
        description: "AWS Region to Deploy Resources"
        required: true 
        default: "eu-north-1"

  
jobs:
  terraform:
    runs-on: ubuntu-latest 

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: ${{ inputs.aws_region }}

      # Terraform Variables
      TF_VAR_aws_region: ${{ inputs.aws_region }}
    
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: ./${{ inputs.working_directory }}
        run: terraform init 

      - name: Terraform Validate
        working-directory: ./${{ inputs.working_directory }}
        run: terraform validate 

      - name: Terraform Plan
        working-directory: ./${{ inputs.working_directory }}
        run: terraform plan 

      - name: Terraform Apply
        working-directory: ./${{ inputs.working_directory }}
        run: terraform apply -auto-approve

